# Generated by Django 5.1.6 on 2025-03-07 06:21

import GPS_App.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPS_App', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('color', models.CharField(default=GPS_App.models.generate_random_color, max_length=7, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'device_config',
                'db_table': 'device_config',
            },
        ),
    ]
