# Generated by Django 5.1.6 on 2025-03-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPS_App', '0003_deviceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_logs',
            name='actual_date_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
