# Generated by Django 5.1.6 on 2025-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPS_App', '0004_device_logs_actual_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_logs',
            name='is_sound_play',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
